endpoints:
  - name: shopping-list                 # Name of your endpoint, can be anything
    url: ec2-3-72-9-218.eu-central-1.compute.amazonaws.com
    interval: 5m                  # Duration to wait between every status check (default: 60s)
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[BODY].status == UP"     # The json path "$.status" must be equal to UP
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

