- hosts: all

tasks:
    - name: Copy file with new permissions
      ansible.builtin.copy:
        src: gatus/config.yaml
        dest: /home/ubuntu/config/config.yaml
        mode: '0644'
        owner: ubuntu
        group: ubuntu