- hosts: all

tasks:
    - name: Copy file with new permissions
      ansible.builtin.copy:
        src: ansible/gatus/config.yaml
        dest: config.yaml
        mode: '0644'
        owner: ubuntu
        group: ubuntu